eShop/Areas/Admin/ViewModels/ProductCategory/AddOrUpdateCategoryVM.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace eShop.Areas.Admin.ViewModels.ProductCategory
{
	public class AddOrUpdateCategoryVM
	{
		public int Id { get; set; }

		[Required(ErrorMessage = "{0} là bắt buộc")]
		[MinLength(3, ErrorMessage = "{0} không được ít hơn 3 ký tự")]
		[DisplayName("Tên danh mục")]
		public string Name { get; set; }
	}
}

eShop/Areas/Admin/ViewModels/ProductCategory/ListItemCategoryVM.cs
namespace eShop.Areas.Admin.ViewModels.ProductCategory
{
	public class ListItemCategoryVM
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public DateTime? CreatedAt { get; set; }
	}
}

eShop/ViewModels/ErrorViewModel.cs
namespace eShop.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

eShop/Areas/Admin/Controllers/BaseController.cs
using AutoMapper;
using eShop.Database;
using Microsoft.AspNetCore.Mvc;

namespace eShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class BaseController : Controller
	{
		protected readonly AppDbContext _db;
		protected readonly IMapper _mapper;
		public BaseController(AppDbContext db, IMapper mapper)
		{
			_db = db;
			_mapper = mapper;
		}
	}
}

eShop/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace eShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

eShop/Areas/Admin/Controllers/ProductCategoryController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using eShop.Areas.Admin.ViewModels.ProductCategory;
using eShop.Database;
using eShop.Database.Entities;
using eShop.WebConfig;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eShop.Areas.Admin.Controllers
{
	public class ProductCategoryController : BaseController
	{
		public ProductCategoryController(AppDbContext db, IMapper mapper) : base(db, mapper)
		{
		}

		public async Task<IActionResult> Index()
		{
			var data = await _db.ProductCategories
				.ProjectTo<ListItemCategoryVM>(AutoMapperProfile.categoryConf)
				.OrderByDescending(x => x.Id)
				.ToListAsync();
			return View(data);
		}

		public async Task<IActionResult> CreateOrUpdate(int? id = 0)
		{
			var title = "Thêm";
			if (id != 0)
			{
				title = "Sửa";
				var category = await _db.ProductCategories.FindAsync(id);
				if (category == null)
				{
					return RedirectToAction(nameof(Index));
				}
				var data = _mapper.Map<AddOrUpdateCategoryVM>(category);
				ViewBag.Title = title;
				return View(data);
			}
			ViewBag.Title = title;
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> CreateOrUpdate(AddOrUpdateCategoryVM model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}
			if (model.Id > 0)
			{
				var data = await _db.ProductCategories.FindAsync(model.Id);
				if (data == null)
				{
					return RedirectToAction(nameof(Index));
				}

				_mapper.Map<AddOrUpdateCategoryVM, ProductCategory>(model, data);
				data.UpdatedAt = DateTime.Now;
				_db.ProductCategories.Update(data);
				await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			var category = _mapper.Map<ProductCategory>(model);
			category.UpdatedAt = DateTime.Now;
			category.CreatedAt = DateTime.Now;
			await _db.ProductCategories.AddAsync(category);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == 0)
			{
				return RedirectToAction(nameof(Index));
			}
			var data = await _db.ProductCategories.FindAsync(id);
			if (data == null)
			{
				return RedirectToAction(nameof(Index));
			}
			if (await _db.Products.AnyAsync(x => x.CategoryId == id))
			{
				TempData["Error"] = "Danh mục có chứa sản phẩm, không thể xóa!";
				return RedirectToAction(nameof(Index));
			}

			_db.ProductCategories.Remove(data);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
	}
}

eShop/Controllers/HomeController.cs
using eShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace eShop.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

eShop/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Home admin</h1>

eShop/Areas/Admin/Views/ProductCategory/CreateOrUpdate.cshtml
@model eShop.Areas.Admin.ViewModels.ProductCategory.AddOrUpdateCategoryVM
@{
	ViewData["Title"] =  $"{ViewBag.Title} danh mục";
}

<h1>@ViewBag.Title</h1>

@{ 
	var id = Model?.Id != null ? Model.Id : 0;
	var name = Model?.Name != null ? Model.Name : "";
}

<div class="row">
	<div class="col-6">
		<form method="post" asp-action="CreateOrUpdate" class="mb-3" autocomplete="off">
			<div asp-validation-summary="All" class="text-danger"></div>
			<input type="hidden" asp-for="Id" value="@id" />
			<div class="mb-3">
				<label asp-for="Name" class="form-label"></label>
				<input asp-for="Name" class="form-control" value="@name">
			</div>
			<div>
				<button class="btn btn-primary" type="submit">@ViewBag.Title</button>
				<button class="btn btn-light" type="reset">Nhập lại</button>
			</div>
		</form>
		<a class="btn btn-outline-info" asp-controller="ProductCategory" asp-action="Index">Về trang danh sách</a>
	</div>
</div>

eShop/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<eShop.Areas.Admin.ViewModels.ProductCategory.ListItemCategoryVM>

@{
	ViewData["Title"] = "Danh mục";
}

<h1 class="text-center">Danh mục</h1>

<a asp-controller="ProductCategory" asp-action="CreateOrUpdate" class="btn btn-primary mb-3">Thêm danh mục</a>

@if (TempData["Error"] != null)
{
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>@TempData["Error"]</strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

<table class="table table-hover table-bordered">
	<thead class="table-dark">
		<tr>
			<th>Id</th>
			<th>Tên danh mục</th>
			<th>Ngày tạo</th>
			<th>Thao tác</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Name</td>
				<td>@item.CreatedAt?.ToString("dd/MM/yyyy")</td>
				<td style="width: 1%; white-space: nowrap;">
					<a asp-action="CreateOrUpdate" asp-route-id="@item.Id" class="btn btn-success">Sửa</a>
					<a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Xác nhận xóa?')" class="btn btn-danger">Xóa</a>
				</td>
			</tr>
		}
	</tbody>
</table>

eShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - eShop</title>

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/admin/site.css" asp-append-version="true" />
	<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">eShop</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductCategory" asp-action="Index">Danh mục</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - eShop - <a asp-area="Admin" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>


	<script src="~/lib/axios/axios.min.js"></script>
	<script src="~/lib/vue/vue.global.min.js"></script>
	<script src="~/lib/sweetalert/sweetalert.min.js"></script>
	<script src="~/lib/font-awesome/js/all.min.js"></script>

	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

eShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>